# Generated by Django 5.1.7 on 2025-04-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_profiles', 'Can watch profiles another users'), ('can_edit_profiles', 'Can edit profiles another users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
