# Generated by Django 5.1.7 on 2025-03-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=150, verbose_name='nickname')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='is_vaccinated')),
                ('is_tail', models.BooleanField(default=False, verbose_name='is_tail')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('profile_of_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('street', models.CharField(max_length=50, verbose_name='street')),
                ('number_of_house', models.CharField(max_length=10, verbose_name='number_of_house')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=100, verbose_name='species')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalWool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wool', models.BooleanField(default=False, verbose_name='wool')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
            ],
        ),
    ]
