# Generated by Django 5.1.7 on 2025-03-27 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animaladdress',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='animal_species', to='animals.animalspecies'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_wool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='animal_wool', to='animals.animalwool'),
        ),
    ]
