# Generated by Django 5.1.7 on 2025-03-28 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date_registration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of registration'),
        ),
    ]
