# Generated by Django 5.1.7 on 2025-03-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_date_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_registration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
